openapi: 3.0.0
info:
  title: ElencoProfessionisti
  version: "1.0.0"
  description: >-
    API per l'acquisizione dell'elenco dei professionisti della Regione Umbria.
    Per maggiori informazioni sull'elenco regionale delle imprese consultare
    http://www.regione.umbria.it/opere-pubbliche/consulta-l-elenco . L'utilizzo
    di questa API è libero e non richiede alcuna sottoscrizione

paths:
  /elenco-professionisti:
    get:
      responses:
        '200':
          description: Chiamata effettuata
          content:
            '*/*':
              schema:
                type: object
                title: Lista tipologie per professionista
                required:
                  - professionisti
                properties:
                  professionisti:
                    title: Professionisti
                    type: object
                    required:
                      - professionista
                    properties:
                      professionista:
                        type: array
                        items:
                          $ref: '#/components/schemas/Professionista'
      summary: >-
        Elenco regionale dei professionisti da invitare alle procedure negoziate
        per l'affidamento di servizi attinenti all'architettura e all'ingegneria
        di importo inferiore a centomila euro.
      x-auth-type: None
      x-throttling-tier: Unlimited
servers:
  - url: 'https://api.regione.umbria.it:443/elencoprofessionisti/1.0'
  - url: 'http://api.regione.umbria.it:443/elencoprofessionisti/1.0'
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://api.regione.umbria.it:443/authorize'
          scopes: {}
  schemas:
    Professionista:
      title: ProfessionistaItem
      required:
        - soggetto
        - codice-fiscale-piva
        - recapito
        - id-profilo
        - profilo
        - numero-domanda
        - id-fascia-importo
        - descrizione-fascia-importo
        - id-tipologia-servizio
        - descrizione-tipologia-servizio
      properties:
        soggetto:
          type: string
        codice-fiscale-piva:
          type: string
        recapito:
          type: string
        id-profilo:
          type: string
        profilo:
          type: string
        numero-domanda:
          type: string
        id-fascia-importo:
          type: string
        descrizione-fascia-importo:
          type: string
        id-tipologia-servizio:
          type: string
        descrizione-tipologia-servizio:
          type: string