swagger: '2.0'
info:
  contact:
    email: robipolli@gmail.com
    name: Roberto Polli
    url: 'https://twitter.com/ioggstream'
  description: |
    Dictionaries are versioned key-value store that you can
      retrieve via API. For each dictionary you can:
      - get metadata infos
      - retrieve a paged subset
      - get a single entry via an unique key
      - find entries by a given key (which could not be unique)

    Despite http://zalando.github.io/restful-api-guidelines/index.html#160
        we use pagination as it's more intuitive for this use case.
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  termsOfService: 'http://swagger.io/terms/'
  title: |
    Core Vocabularies API
  version: 0.0.1
  x-api-id: b9ec7026-5da5-4db6-a959-fce72db5de64
  x-audience: |
    Definire qui l'audience delle API
host: virtserver.swaggerhub.com
basePath: /robipolli/core-vocabularies/0.0.1
schemes:
  - https
paths:
  /dictionaries:
    get:
      produces:
        - application/json
      parameters:
        - description: The indexed key to search with.
          in: query
          name: name
          required: false
          type: string
        - $ref: >-
            https://raw.githubusercontent.com/ioggstream/openapi-samples/master/openapi-v3/schema/components.yaml#components/parameters/limit
        - $ref: >-
            https://raw.githubusercontent.com/ioggstream/openapi-samples/master/openapi-v3/schema/components.yaml#components/parameters/offset
        - $ref: >-
            https://raw.githubusercontent.com/ioggstream/openapi-samples/master/openapi-v3/schema/components.yaml#components/parameters/sort
      responses:
        '200':
          description: >
            A list of dictionaries.

            Headers secondo
            http://zalando.github.io/restful-api-guidelines/index.html#132
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/x-components/headers/X-Rate-Limit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/x-components/headers/X-Rate-Limit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/x-components/headers/X-Rate-Limit-Reset'
          links:
            NextDictionaries:
              $ref: '#/x-components/links/NextDictionaries'
          schema:
            $ref: '#/definitions/Dictionaries'
      tags:
        - public
      description: |
        Shows a list of supported dictionaries.
      operationId: getDictionaries
      summary: Get informations about provided dictionaries.
  '/dictionaries/{dictionary_name}':
    get:
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: |
            Retrieve information from a dictionary.
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/x-components/headers/X-Rate-Limit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/x-components/headers/X-Rate-Limit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/x-components/headers/X-Rate-Limit-Reset'
          schema:
            $ref: '#/definitions/Dictionary'
        '400':
          $ref: >-
            '#/x-components/responses/400BadRequest'
        '404':
          $ref: >-
            '#/x-components/responses/404NotFound'
        default:
          $ref: >-
            '#/x-components/responses/default'
      tags:
        - public
      description: |
        Retrieve available dictionary version and URI.
      operationId: getDictionary
      summary: Get informations about a dictionary.
    post:
      produces:
        - application/json
      parameters: []
      responses:
        '201':
          description: |
            A new version of the table have been created.
          links:
            GetNewVersion:
              parameters:
                version: '$response.body#/version'
              description: >
                Il valore di  `v` ritornato dalla response puo' essere passato
                via GET `/comuni?v={v}` per interrogare l'ultima versione delle
                API .
              operationId: getDictionaries
          schema:
            $ref: '#/definitions/Dictionary'
        '404':
          $ref: >-
            '#/x-components/responses/404NotFound'
        default:
          $ref: >-
            '#/x-components/responses/default'
      tags:
        - admins
      operationId: uploadDictionary
      summary: |
        Upload a new (version of a) dictionary eventually creating
        a new dictionary. The passed csv file contains a trailing
        line with the expected line count. If the schema does not match
        previous version, an error is returned.
  '/dictionaries/{dictionary_name}/meta':
    get:
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: |
            Retrieve information from a dictionary.
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/x-components/headers/X-Rate-Limit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/x-components/headers/X-Rate-Limit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/x-components/headers/X-Rate-Limit-Reset'
          schema:
            $ref: '#/definitions/Dictionary'
        '400':
          $ref: >-
            '#/x-components/responses/400BadRequest'
        '404':
          $ref: >-
            '#/x-components/responses/404NotFound'
        default:
          $ref: >-
            '#/x-components/responses/default'
      tags:
        - public
      description: |
        Retrieve available dictionary version and URI:
        foo bar
      operationId: getDictionaryMeta
      summary: Get meta informations about a dictionary.
  '/dictionaries/{dictionary_name}/{version}':
    get:
      produces:
        - application/json
      parameters:
        - description: The indexed key to search with.
          in: query
          name: name
          required: false
          type: string
        - $ref: >-
            https://raw.githubusercontent.com/ioggstream/openapi-samples/master/openapi-v3/schema/components.yaml#components/parameters/limit
        - $ref: >-
            https://raw.githubusercontent.com/ioggstream/openapi-samples/master/openapi-v3/schema/components.yaml#components/parameters/offset
        - $ref: >-
            https://raw.githubusercontent.com/ioggstream/openapi-samples/master/openapi-v3/schema/components.yaml#components/parameters/sort
      responses:
        '200':
          description: |
            Retrieve dictionary metadata
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/x-components/headers/X-Rate-Limit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/x-components/headers/X-Rate-Limit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/x-components/headers/X-Rate-Limit-Reset'
          links:
            NextDictionaries:
              $ref: '#/x-components/links/NextDictionaries'
          schema:
            $ref: '#/definitions/Entry'
        '400':
          $ref: >-
            '#/x-components/responses/400BadRequest'
        '404':
          $ref: >-
            '#/x-components/responses/404NotFound'
        default:
          $ref: >-
            '#/x-components/responses/default'
      tags:
        - public
      description: |
        Retrieve paged entries from a Table.
      operationId: getDictionary
      summary: Get entries from a dictionary.
  '/dictionaries/{dictionary_name}/{version}/{entry_key}':
    get:
      produces:
        - application/json
      parameters:
        - description: The indexed key to search with.
          in: query
          name: name
          required: false
          type: string
        - $ref: >-
            https://raw.githubusercontent.com/ioggstream/openapi-samples/master/openapi-v3/schema/components.yaml#components/parameters/limit
        - $ref: >-
            https://raw.githubusercontent.com/ioggstream/openapi-samples/master/openapi-v3/schema/components.yaml#components/parameters/offset
        - $ref: >-
            https://raw.githubusercontent.com/ioggstream/openapi-samples/master/openapi-v3/schema/components.yaml#components/parameters/sort
      responses:
        '200':
          description: |
            Retrieves a dictionary entry.
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/x-components/headers/X-Rate-Limit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/x-components/headers/X-Rate-Limit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/x-components/headers/X-Rate-Limit-Reset'
          links:
            NextDictionaries:
              $ref: '#/x-components/links/NextDictionaries'
          schema:
            $ref: '#/definitions/Entries'
        '400':
          $ref: >-
            '#/x-components/responses/400BadRequest'
        '404':
          $ref: >-
            '#/x-components/responses/404NotFound'
        '429':
          $ref: >-
            '#/x-components/responses/429TooManyRequests'
        '503':
          $ref: >-
            '#/x-components/responses/503ServiceUnavailable'
        default:
          $ref: >-
            '#/x-components/responses/default'
      tags:
        - public
      description: ''
      operationId: getEntry
      summary: Get a Table entry
definitions:
  Dictionaries:
    properties:
      item:
        items:
          $ref: '#/definitions/Dictionary'
        type: array
      offset:
        example: 5
        format: int32
        type: integer
      offset_next:
        example: 5
        format: int32
        type: integer
    required:
      - items
      - offset
      - offset_next
  Dictionary:
    description: |
      Reference to a dictionary, that is a versioned table.
    properties:
      last_version:
        example: 1.0.0
        type: string
      name:
        example: cities
        type: string
      uri:
        example: 'http://dictionaries-beta.api.example.com/dictionaries/cities'
        format: uri
        type: string
    required:
      - name
      - last_version
      - uri
  Entries:
    properties:
      item:
        items:
          $ref: '#/definitions/Entry'
        type: array
      offset:
        example: 5
        format: int32
        type: integer
      offset_next:
        example: 5
        format: int32
        type: integer
    required:
      - items
      - offset
      - offset_next
  Entry:
    properties:
      data:
        example:
          codice_catastale: E472
          codice_istat: 059011
          nome: Latina
          nome_traslitterato: LATINA
          provincia: LT
        type: object
      key:
        example: E472-2007
        type: string
      name:
        example: Latina
        type: string
      version:
        example: 1.0.0
        type: string
    required:
      - key
      - uuid
      - name
      - version
      - data
  Error:
    $ref: >-
      https://raw.githubusercontent.com/ioggstream/openapi-samples/master/openapi-v3/schema/components.yaml#components/schemas/Error
  Table:
    description: >
      Dictionary data, freely inspired by
      https://github.com/italia/daf-ontologie-vocabolari-controllati/
    properties:
      name:
        example: cities
        type: string
      ttl:
        description: Seconds to the invalidation of the API.
        format: int32
        type: integer
      uri:
        example: 'http://dictionaries-beta.api.example.com/dictionaries/cities/v1.0'
        format: uri
        type: string
      version:
        example: 1.0.0
        type: string
    required:
      - name
      - version
      - uri
      - ttl
tags:
  - description: Create and update dictionaries
    name: admins
  - description: Retrieve dictionaries
    name: public
x-components:
  parameters:
    limit:
      $ref: >-
        https://raw.githubusercontent.com/ioggstream/openapi-samples/master/openapi-v3/schema/components.yaml#components/parameters/limit
    name:
      description: The indexed key to search with.
      in: query
      name: name
      required: false
      type: string
    offset:
      $ref: >-
        https://raw.githubusercontent.com/ioggstream/openapi-samples/master/openapi-v3/schema/components.yaml#components/parameters/offset
    sort:
      $ref: >-
        https://raw.githubusercontent.com/ioggstream/openapi-samples/master/openapi-v3/schema/components.yaml#components/parameters/sort
  responses:
    400BadRequest:
      $ref: >-
        https://raw.githubusercontent.com/ioggstream/openapi-samples/master/openapi-v3/schema/components.yaml#components/responses/400BadRequest
    404NotFound:
      $ref: >-
        https://raw.githubusercontent.com/ioggstream/openapi-samples/master/openapi-v3/schema/components.yaml#components/responses/404NotFound
    429TooManyRequests:
      $ref: >-
        https://raw.githubusercontent.com/ioggstream/openapi-samples/master/openapi-v3/schema/components.yaml#components/responses/429TooManyRequests
    503ServiceUnavailable:
      $ref: >-
        https://raw.githubusercontent.com/ioggstream/openapi-samples/master/openapi-v3/schema/components.yaml#components/responses/503ServiceUnavailable
    default:
      $ref: >-
        https://raw.githubusercontent.com/ioggstream/openapi-samples/master/openapi-v3/schema/components.yaml#components/responses/default
  headers:
    X-Rate-Limit-Limit:
      $ref: >-
        https://raw.githubusercontent.com/ioggstream/openapi-samples/master/openapi-v3/schema/components.yaml#components/headers/X-Rate-Limit-Limit
    X-Rate-Limit-Remaining:
      $ref: >-
        https://raw.githubusercontent.com/ioggstream/openapi-samples/master/openapi-v3/schema/components.yaml#components/headers/X-Rate-Limit-Remaining
    X-Rate-Limit-Reset:
      $ref: >-
        https://raw.githubusercontent.com/ioggstream/openapi-samples/master/openapi-v3/schema/components.yaml#components/headers/X-Rate-Limit-Reset
  links:
    NextDictionaries:
      parameters:
        offset: '$response.body#/offset_next'
      operationId: getDictionaries

