swagger: '2.0'
info:
  contact:
    email: robipolli@gmail.com
    name: Roberto Polli
    url: 'https://twitter.com/ioggstream'
  description: |
    Dictionaries are versioned key-value store that you can
      retrieve via API. For each dictionary you can:
      - get metadata infos
      - retrieve a paged subset
      - get a single entry via an unique key
      - find entries by a given key (which could not be unique)

      Dictionary structure is the following:
      - Dictionary: has a single name and many versions
        - Table: it's a specific version of a dictionary. May
            expire
            - Entry: it's the actual data contained in a table.

    Despite http://zalando.github.io/restful-api-guidelines/index.html#160
        we use pagination as it's more intuitive for this use case.
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  termsOfService: 'http://swagger.io/terms/'
  title: |
    Core Vocabularies API
  version: 0.0.1
  x-api-id: b9ec7026-5da5-4db6-a959-fce72db5de64
  x-audience: |
    Definire qui l'audience delle API
host: virtserver.swaggerhub.com
basePath: /robipolli/core-vocabularies/0.0.1
schemes:
  - https
paths:
  /dictionaries:
    get:
      produces:
        - application/json
      parameters:
        - description: The indexed key to search with.
          example: Latina
          in: query
          name: name
          required: false
          type: string
        - $ref: 'schema/components.yaml#x-components/parameters/limit'
        - $ref: 'schema/components.yaml#x-components/parameters/offset'
        - $ref: 'schema/components.yaml#x-components/parameters/sort'
      responses:
        '200':
          description: >
            A list of Dictionaries.

            Headers secondo
            http://zalando.github.io/restful-api-guidelines/index.html#132
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/x-components/headers/X-Rate-Limit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/x-components/headers/X-Rate-Limit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/x-components/headers/X-Rate-Limit-Reset'
          schema:
            $ref: '#/definitions/Dictionaries'
      tags:
        - public
      description: |
        Shows a list of supported dictionaries.
      operationId: getDictionaries
      summary: Get informations about provided dictionaries.
  '/dictionaries/{dictionary_name}':
    get:
      produces:
        - application/json
      parameters:
        - description: The name of the dictionary
          example: cities
          in: path
          name: dictionary_name
          required: true
          type: string
      responses:
        '200':
          description: |
            Retrieve information from a dictionary.
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/x-components/headers/X-Rate-Limit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/x-components/headers/X-Rate-Limit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/x-components/headers/X-Rate-Limit-Reset'
          schema:
            $ref: '#/definitions/Dictionary'
        '400':
          $ref: 'schema/components.yaml#x-components/responses/400BadRequest'
        '404':
          $ref: 'schema/components.yaml#x-components/responses/404NotFound'
        default:
          $ref: 'schema/components.yaml#x-components/responses/default'
      tags:
        - public
      description: |
        Retrieve available dictionary version and URI.
      operationId: getDictionary
      summary: Get informations about a dictionary.
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - description: Use MarkDown here!
          in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/TableData'
      responses:
        '201':
          description: |
            A new version of the table have been created.
          schema:
            $ref: '#/definitions/Table'
        '404':
          $ref: 'schema/components.yaml#x-components/responses/404NotFound'
        default:
          $ref: 'schema/components.yaml#x-components/responses/default'
      tags:
        - admins
      operationId: uploadDictionary
      summary: |
        Upload a new (version of a) dictionary eventually creating
        a new dictionary. The passed csv file contains a trailing
        line with the expected line count. If the schema does not match
        previous version, an error is returned.
  '/dictionaries/{dictionary_name}/meta':
    get:
      produces:
        - application/json
      parameters:
        - description: The name of the dictionary
          example: cities
          in: path
          name: dictionary_name
          required: true
          type: string
      responses:
        '200':
          description: |
            Retrieve information from a dictionary.
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/x-components/headers/X-Rate-Limit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/x-components/headers/X-Rate-Limit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/x-components/headers/X-Rate-Limit-Reset'
          schema:
            $ref: '#/definitions/Dictionary'
        '400':
          $ref: 'schema/components.yaml#x-components/responses/400BadRequest'
        '404':
          $ref: 'schema/components.yaml#x-components/responses/404NotFound'
        default:
          $ref: 'schema/components.yaml#x-components/responses/default'
      tags:
        - public
      description: |
        Retrieve available dictionary version and URI:
        foo bar
      operationId: getDictionaryMeta
      summary: Get meta informations about a dictionary.
  '/dictionaries/{dictionary_name}/{version}':
    get:
      produces:
        - application/json
      parameters:
        - description: The name of the dictionary
          example: cities
          in: path
          name: dictionary_name
          required: true
          type: string
        - description: A specific version of a dictionary.
          example: 137
          in: path
          name: version
          required: true
          type: integer
        - description: The indexed key to search with.
          example: Latina
          in: query
          name: name
          required: false
          type: string
        - $ref: 'schema/components.yaml#x-components/parameters/limit'
        - $ref: 'schema/components.yaml#x-components/parameters/offset'
        - $ref: 'schema/components.yaml#x-components/parameters/sort'
      responses:
        '200':
          description: |
            Retrieve dictionary metadata
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/x-components/headers/X-Rate-Limit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/x-components/headers/X-Rate-Limit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/x-components/headers/X-Rate-Limit-Reset'
          schema:
            $ref: '#/definitions/Entry'
        '400':
          $ref: 'schema/components.yaml#x-components/responses/400BadRequest'
        '404':
          $ref: 'schema/components.yaml#x-components/responses/404NotFound'
        default:
          $ref: 'schema/components.yaml#x-components/responses/default'
      tags:
        - public
      description: |
        Retrieve paged entries from a Table.
      operationId: getDictionary
      summary: Get entries from a dictionary.
  '/dictionaries/{dictionary_name}/{version}/{entry_key}':
    get:
      produces:
        - application/json
      parameters:
        - description: The name of the dictionary
          example: cities
          in: path
          name: dictionary_name
          required: true
          type: string
        - description: A specific version of a dictionary.
          example: 137
          in: path
          name: version
          required: true
          type: integer
        - description: The entry key
          example: E472-2007
          in: path
          name: entry_key
          required: true
          type: string
      responses:
        '200':
          description: |
            Returns the given entry.
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/x-components/headers/X-Rate-Limit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/x-components/headers/X-Rate-Limit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/x-components/headers/X-Rate-Limit-Reset'
          schema:
            $ref: '#/definitions/Entries'
        '400':
          $ref: 'schema/components.yaml#x-components/responses/400BadRequest'
        '404':
          $ref: 'schema/components.yaml#x-components/responses/404NotFound'
        '429':
          $ref: 'schema/components.yaml#x-components/responses/429TooManyRequests'
        '503':
          $ref: 'schema/components.yaml#x-components/responses/503ServiceUnavailable'
        default:
          $ref: 'schema/components.yaml#x-components/responses/default'
      tags:
        - public
      description: Retrieve an entry from a Table.
      operationId: getEntry
      summary: Get a Table entry
  '/table/{table_uuid}/':
    get:
      produces:
        - application/json
      parameters:
        - description: The table uuid
          example: 2b356821-868e-4274-9c8e-ca119dd097df
          in: path
          name: table_uuid
          required: true
          type: string
        - description: The indexed key to search with.
          example: Latina
          in: query
          name: name
          required: false
          type: string
        - $ref: 'schema/components.yaml#x-components/parameters/limit'
        - $ref: 'schema/components.yaml#x-components/parameters/offset'
        - $ref: 'schema/components.yaml#x-components/parameters/sort'
      responses:
        '200':
          description: |
            Retrieve table data
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/x-components/headers/X-Rate-Limit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/x-components/headers/X-Rate-Limit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/x-components/headers/X-Rate-Limit-Reset'
          schema:
            $ref: '#/definitions/Entries'
        '400':
          $ref: 'schema/components.yaml#x-components/responses/400BadRequest'
        '404':
          $ref: 'schema/components.yaml#x-components/responses/404NotFound'
        default:
          $ref: 'schema/components.yaml#x-components/responses/default'
      tags:
        - public
      description: |
        Retrieve paged entries from a Table.
      operationId: getTableEntries
      summary: Get entries from a given table.
  '/table/{table_uuid}/{entry_key}':
    get:
      produces:
        - application/json
      parameters:
        - description: The table uuid
          example: 2b356821-868e-4274-9c8e-ca119dd097df
          in: path
          name: table_uuid
          required: true
          type: string
        - description: The entry key
          example: E472-2007
          in: path
          name: entry_key
          required: true
          type: string
      responses:
        '200':
          description: |
            Returns the given entry.
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/x-components/headers/X-Rate-Limit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/x-components/headers/X-Rate-Limit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/x-components/headers/X-Rate-Limit-Reset'
          schema:
            $ref: '#/definitions/Entries'
        '400':
          $ref: 'schema/components.yaml#x-components/responses/400BadRequest'
        '404':
          $ref: 'schema/components.yaml#x-components/responses/404NotFound'
        '429':
          $ref: 'schema/components.yaml#x-components/responses/429TooManyRequests'
        '503':
          $ref: 'schema/components.yaml#x-components/responses/503ServiceUnavailable'
        default:
          $ref: 'schema/components.yaml#x-components/responses/default'
      tags:
        - public
      description: Retrieve an entry from a Table.
      operationId: getEntryByTable
      summary: Get a Table entry
  /tables:
    get:
      produces:
        - application/json
      parameters:
        - description: The name of the dictionary
          example: cities
          in: query
          name: dictionary_name
          type: string
        - $ref: 'schema/components.yaml#x-components/parameters/limit'
        - $ref: 'schema/components.yaml#x-components/parameters/offset'
        - $ref: 'schema/components.yaml#x-components/parameters/sort'
      responses:
        '200':
          description: |
            A list of Tables.
          headers:
            X-Rate-Limit-Limit:
              $ref: '#/x-components/headers/X-Rate-Limit-Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/x-components/headers/X-Rate-Limit-Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/x-components/headers/X-Rate-Limit-Reset'
          schema:
            $ref: '#/definitions/Tables'
      tags:
        - public
      description: |
        Shows a list of supported tables matching the given name.
      operationId: getTables
      summary: Get informations about exiting tables.
definitions:
  Dictionaries:
    properties:
      item:
        items:
          $ref: '#/definitions/Dictionary'
        type: array
      offset:
        example: 5
        format: int32
        type: integer
      offset_next:
        example: 10
        format: int32
        type: integer
    required:
      - items
      - offset
      - offset_next
  Dictionary:
    description: |
      Reference to a dictionary, that is a multi-versioned table.
    properties:
      description:
        example: |-
          Which data is contained in the dictionary? Cities? Foreign countries?
          Healtcare codes?
        type: string
      last_version:
        example: 134
        type: integer
      name:
        example: cities
        type: string
      uri:
        example: 'http://dictionaries-beta.api.example.com/dictionaries/cities'
        format: uri
        type: string
    required:
      - name
      - description
      - last_version
      - uri
  Entries:
    properties:
      item:
        items:
          $ref: '#/definitions/Entry'
        type: array
      offset:
        description: Current offset (eg. entries 50 to 99)
        example: 50
        format: int32
        type: integer
      offset_next:
        description: |-
          Offset for the next page (eg. entries from 100 to 149).
          This could be a link too in HATEOAS.
        example: 100
        format: int32
        type: integer
      table_uri:
        example: >-
          http://dictionaries-beta.api.example.com/table/2b356821-868e-4274-9c8e-ca119dd097df
        format: uri
        type: string
    required:
      - items
      - offset
      - offset_next
  Entry:
    properties:
      data:
        example:
          codice_catastale: E472
          codice_istat: 059011
          nome: Latina
          nome_traslitterato: LATINA
          provincia: LT
        type: object
      key:
        description: |-
          An unique ID for the entry in the given table. This may have
            a semantic meaning or could be just an UUID.
        example: E472-2007
        type: string
      name:
        description: Searchable string.
        example: Latina
        type: string
    required:
      - key
      - data
  Error:
    $ref: 'schema/components.yaml#x-components/schemas/Error'
  Table:
    description: |
      Versioned dictionary.
    properties:
      name:
        example: cities
        type: string
      table_uri:
        example: >-
          http://dictionaries-beta.api.example.com/table/2b356821-868e-4274-9c8e-ca119dd097df
        format: uri
        type: string
      ttl:
        description: Seconds to the invalidation of the API.
        format: int32
        type: integer
      uri:
        example: 'http://dictionaries-beta.api.example.com/dictionaries/cities/137'
        format: uri
        type: string
      uuid:
        example: 2b356821-868e-4274-9c8e-ca119dd097df
        format: uuid
        type: string
      version:
        example: 137
        type: integer
    required:
      - name
      - version
      - uri
      - uuid
      - ttl
  TableData:
    description: >
      Dictionary data, freely inspired by
      https://github.com/italia/daf-ontologie-vocabolari-controllati/
    properties:
      data:
        items:
          $ref: '#/definitions/Entry'
        type: array
      name:
        example: cities
        type: string
      ttl:
        description: Seconds to the invalidation of the API.
        format: int32
        type: integer
    required:
      - name
      - ttl
      - data
  Tables:
    properties:
      item:
        items:
          $ref: '#/definitions/Table'
        type: array
      offset:
        example: 5
        format: int32
        type: integer
      offset_next:
        example: 10
        format: int32
        type: integer
    required:
      - items
      - offset
      - offset_next
tags:
  - description: Create and update dictionaries
    name: admins
  - description: Retrieve dictionaries
    name: public
x-components:
  parameters:
    dictionary_name:
      description: The name of the dictionary
      example: cities
      in: query
      name: dictionary_name
      type: string
    dictionary_name_path:
      description: The name of the dictionary
      example: cities
      in: path
      name: dictionary_name
      required: true
      type: string
    entry_key_path:
      description: The entry key
      example: E472-2007
      in: path
      name: entry_key
      required: true
      type: string
    limit:
      $ref: 'schema/components.yaml#x-components/parameters/limit'
    name:
      description: The indexed key to search with.
      example: Latina
      in: query
      name: name
      required: false
      type: string
    offset:
      $ref: 'schema/components.yaml#x-components/parameters/offset'
    sort:
      $ref: 'schema/components.yaml#x-components/parameters/sort'
    table_uuid_path:
      description: The table uuid
      example: 2b356821-868e-4274-9c8e-ca119dd097df
      in: path
      name: table_uuid
      required: true
      type: string
    version_path:
      description: A specific version of a dictionary.
      example: 137
      in: path
      name: version
      required: true
      type: integer
  responses:
    400BadRequest:
      $ref: 'schema/components.yaml#x-components/responses/400BadRequest'
    404NotFound:
      $ref: 'schema/components.yaml#x-components/responses/404NotFound'
    429TooManyRequests:
      $ref: 'schema/components.yaml#x-components/responses/429TooManyRequests'
    503ServiceUnavailable:
      $ref: 'schema/components.yaml#x-components/responses/503ServiceUnavailable'
    default:
      $ref: 'schema/components.yaml#x-components/responses/default'
  headers:
    X-Rate-Limit-Limit:
      $ref: 'schema/components.yaml#x-components/headers/X-Rate-Limit-Limit'
    X-Rate-Limit-Remaining:
      $ref: 'schema/components.yaml#x-components/headers/X-Rate-Limit-Remaining'
    X-Rate-Limit-Reset:
      $ref: 'schema/components.yaml#x-components/headers/X-Rate-Limit-Reset'

