---
openapi: 3.0.2
info:
  title: Osservatorio prezzi carburante
  version: 1.0.0
  description: Osservatorio prezzi carburante
servers:
- url: https://carburanti.mise.gov.it/OssPrezziSearch
paths:
  /ricerca/localita:
    summary: Ricerca prezzi dei carburanti in base a dei criteri.
    description: Ricerca i distributori con i relativi prezzi su base geografica.
    post:
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Ricerca'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Risposta'
          description: Successful response - returns a single `Distributore`.
      operationId: getDistributore
      summary: Get a Distributore
      description: Gets the details of a single instance of a `Distributore`.
components:
  schemas:
    ETRS89Longitude:
      description: >-
        Longitude of a point in the ETRS89 system.
      externalDocs:
        url: http://dati.gov.it/onto/clvapit#long
      type: number
      format: double
      minimum: -180
      maximum: 180
      example: 9.19289
    ETRS89Latitude:
      description: >-
        Latitude of a point in the ETRS89 system.
      externalDocs:
        url: http://dati.gov.it/onto/clvapit#lat
      type: number
      format: double
      minimum: -90
      maximum: 90
      example: 45.492599

    Center:
      description: Il centro della ricerca geografica.
      properties:
        second:
          $ref: '#/components/schemas/Longitude'
        first:
          $ref: '#/components/schemas/Latitude'
    Latitude:
      type: string
      minimum: 0
      example: "41.421054115541715"
    Longitude:
      type: string
      example: "13.107509538531303"
    Risposta:
      properties:
        success:
          type: boolean
          example: true
        priceSort:
          type: boolean
          example: true
        center:
          $ref: '#/components/schemas/Center'
        array:
          type: array
          items:
            $ref: '#/components/schemas/Distributore'
    Distributore:
      title: Root Type for Distributore
      description: Risposta a Ricerca Carburante
      required:
      - carburanti
      - lat
      type: object
      properties:
        lat:
          $ref: '#/components/schemas/Latitude'
        lon:
          $ref: '#/components/schemas/Longitude'
        dIns:
          format: date-time
          type: string
        carburanti:
          type: array
          items:
            $ref: '#/components/schemas/Carburante'
        addr:
          type: string
        bnd:
          type: string
        name:
          description: Nome del distributore
          type: string
        id:
          format: int32
          type: integer
      example:
        lat: "41.37743027724601"
        lon: "13.395387679338455"
        dIns: 2019-08-13 08:47:31
        carburanti:
        - idDettCarbRid: 17818997
          carb: Benzina
          idCarb: 1
          isSelf: 0
          prezzo: "1.484"
        - idDettCarbRid: 24770666
          carb: Benzina
          idCarb: 1
          isSelf: 1
          prezzo: "1.549"
        - idDettCarbRid: 17818993
          carb: Gasolio
          idCarb: 2
          isSelf: 0
          prezzo: "1.317"
        - idDettCarbRid: 24941168
          carb: Gasolio
          idCarb: 2
          isSelf: 1
          prezzo: "1.399"
        addr: VIA PONTE GAGLIARDO 160 04022 - FONDI LT
        bnd: Esso
        name: FONDI GAGLIARDO ESSO
        id: 30613
    Carburante:
      title: Carburante
      description: Informazioni sul costo di un carburante
      type: object
      properties:
        idDettCarbRid:
          format: int32
          type: integer
        carb:
          type: string
        idCarb:
          format: int32
          type: integer
        isSelf:
          format: int32
          type: integer
        prezzo:
          type: string
      example:
        idDettCarbRid: 17818993
        carb: Gasolio
        idCarb: 2
        isSelf: 0
        prezzo: "1.317"
    Ricerca:
      description: Parametri di ricerca per i prezzi di un carburante
      properties:
        region:
          type: number
          example: 9
        province:
          type: string
          example: LT
        town:
          type: string
          example: Latina
        carb:
          type: string
          example: 2-x
        ordPrice:
          enum:
          - asc
          - desc
          type: string
          example: asc
