openapi: 3.0.2
info:
  version: 0.0.2
  title: Gruppo Linee Guida Attribute Authority
  license:
    name: EUPL1.2
  x-summary: Semplice AA in formato OAS
  x-api-id: cace2c1e-588f-438f-b08b-d1a7cd63cc55
  termsOfService: 'https://en.wikipedia.org/wiki/Terms_of_service'
  contact:
    email: robipolli@gmail.com
    name: Roberto Polli
    url: 'https://twitter.com/ioggstream'
  x-audience: |
    Definire qui l'audience delle API
  description: |
    ## Documentazione
    
    Qui è possibile includere tutta la documentazione di quest'API
    Su più righe e più paragrafi.
    ### Note
    Qui posso anche inserire delle note.
x-componenti-comuni:
  common_responses: &common_responses
    '503':
      $ref: 'https://teamdigitale.github.io/openapi/responses/v3.yaml#/503ServiceUnavailable'
    '429':
      $ref: 'https://teamdigitale.github.io/openapi/responses/v3.yaml#/429TooManyRequests'
    default:
      $ref: 'https://teamdigitale.github.io/openapi/responses/v3.yaml#/default'

  throttling_headers: &throttling_headers
    X-RateLimit-Limit:
      $ref: 'https://teamdigitale.github.io/openapi/headers/v3.yaml#/X-RateLimit-Limit'
    X-RateLimit-Remaining:
      $ref: 'https://teamdigitale.github.io/openapi/headers/v3.yaml#/X-RateLimit-Remaining'
    X-RateLimit-Reset:
      $ref: 'https://teamdigitale.github.io/openapi/headers/v3.yaml#/X-RateLimit-Reset'
tags: 
- name: puntuale
  description: Recupero puntuale di un attributo
servers:
  - url: http://attribute.authority.it/
    description: production
  - url: http://beta-attribute.authority.it/
    description: test
paths:
  /utenti-lg-attributi/{fiscalCode}:
    get:
      summary: Info per partecipanti gruppo di lavoro Attribute Authority
      operationId: showUserByFiscalCode
      tags:
        - puntuale
      parameters:
        - $ref: '#/components/parameters/fiscalCode'
      responses:
        '200':
          headers:
            <<: *throttling_headers
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
        '503':
          $ref: 'https://teamdigitale.github.io/openapi/responses/v3.yaml#/503ServiceUnavailable'
        '429':
          $ref: 'https://teamdigitale.github.io/openapi/responses/v3.yaml#/429TooManyRequests'
        default:
          $ref: 'https://teamdigitale.github.io/openapi/responses/v3.yaml#/default'
  /status:
    get:
      summary: URL per testare il funzionamento dell'API
      operationId: status
      tags:
      - pubblico
      responses:
        <<: *common_responses
        '200':
          headers:
            <<: *throttling_headers
          description: Return a successful response in a problem+json
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Problem"
components:
  parameters:
    fiscalCode:
      name: fiscalCode
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/FiscalCode"
  schemas:
    User:
      description: |
        Un utente SPID. 
        
        In questo schema i dati seguono le naming convention
        degli attribuiti spid e non quelli delle ontologie agid. E' da capire
        se ci sono margini di manovra su questo terreno.

      externalDocs:
        description: Riferimenti ad attributi SPID
        url: >-
          https://docs.italia.it/italia/spid/spid-regole-tecniche/it/bozza/attributi.html
      required:
        - fiscalCode
        - name
      properties:
        fiscalCode:
          $ref: "#/components/schemas/FiscalCode"
        name:
          description: |
            Conforme ad attributi spid, ma non a ontologie agid, che
            userebbero il più specifico givenName.
          type: string
          externalDocs:
            url: >-
              https://w3id.org/italia/onto/CPV/givenName
        familyName:
          description: |
            Conforme sia a specifiche spid che ad ontologie agid
          externalDocs:
            url: >-
              https://w3id.org/italia/onto/CPV/familyName
          type: string
    Users:
      type: array
      items:
        $ref: "#/components/schemas/User"
    FiscalCode:
      "$ref": "https://raw.githubusercontent.com/teamdigitale/openapi/master/docs/schemas/tax_code.yaml#/TaxCode"
    Problem:
      "$ref": "https://raw.githubusercontent.com/teamdigitale/openapi/0.0.1/docs/schemas/problem.yaml#/Problem"
